<?php
// THESE CONFIGURATIONS ARE GENERATED AUTOMATICALLY BASED ON config.php.
// YOU SHOULD NOT MODIFY IT UNLESS YOU WANT TO CHANGE FUNCTIONALITY OF THESE CONSTANTS.

define("PAGE_FULL_URL",
			(PAGE_HTTPS ? "https://" : "http://") .
			PAGE_HOST .
			((!PAGE_HTTPS && PAGE_PORT==80 )
				|| (PAGE_HTTPS && PAGE_PORT==443) ? "" : ":" . PAGE_PORT) .
			PAGE_BASE_URI);

?>